<!DOCTYPE html>
<head>
  <title>Contato</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
	<h1>Formulario de Cadastro</h1>
	<p>Faculdade Sumaré</p>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label>Nome:</label>
				<input type="text" class="form-control"></input>
			</div>
			<div class="form-group">
				<label>RA:</label>
				<input type="text" class="form-control"></input>
			</div>
			<div class="form-group">
				<label>Curso:</label>
				<input type="text" class="form-control"></input>
			</div>
			<div class="form-group">
				<label>Semestre:</label>
				<input type="text" class="form-control"></input>
			</div>
			<div class="form-group">
				<label>Mensagem:</label>
				<input type="text" class="form-control"></input>
			</div>
			<div class="form-group">
				<a class="btn btn-primary" href="/">Enviar mensagem</a>
			</div>
		</div>
	</div>
</div>

</body>
</html>
